# Numpy 简介

Numpy (Numerical Python) 是 Python 语言一个重要的扩展库，支持大量的数组与矩阵运算，此外也提供大量的数学函数库，用于模仿数学软件 MatLab 的功能。Numpy 通常与其他库 SciPy（Scientific Python）和 Matplotlib（绘图库）一起使用。

Numpy 的主要特点是：

- 一个强大的 N 维数组对象 ndarray

- 矩阵运算、傅里叶变换、生成随机数功能等

使用 numpy 需要首先导入 numpy 包：

In [1]:
import numpy as np

## 创建数组

用 Numpy 创建数组有多种方法。首先，Numpy 中的``array``函数可以直接将 Python 的 list 类型转化为 Numpy 的数组类型 ndarray。例如，一个一维数组：

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

一个二维数组：

In [6]:
b = [[1, 2], [3, 4]]
a = np.array(b)
a

[[1, 2], [3, 4]]

注意，``array``函数中的小括号中要包括一个用中括号括起来的 list，不能直接写成 np.array(1, 2, 3, 4)。

Numpy 中的``zeros``函数可以创建元素值全为 0 的矩阵，``ones``函数可以创建元素值全为 1 的矩阵，而``empty``函数可以创建一个元素值任意的一个空矩阵。例如：

In [7]:
np.zeros((3, 4)) # 3 行 4 列的零矩阵

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3, 4)) # 3 行 4 列的一矩阵

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.empty((2, 3)) # 2 行 3 列的空矩阵

array([[0.e+000, 3.e-323, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000]])

Numpy 中的``arange``函数可以生成一个等差数列的数组，例如：

In [10]:
np.arange(10) # 生成一个从 0 到 9 之间的数组，默认步长为 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(5, 10) # 生成一个从 5 到 9 之间的数组，默认步长为 1

array([5, 6, 7, 8, 9])

In [12]:
np.arange(5, 10, 2) # 生成一个从 5 到 9 之间的数组，且步长为 2

array([5, 7, 9])

另外一个类似的函数为``linespace``，不同的地方在于：``arange``函数中第三个参数表示等差数组的步长，而``linespace``函数第三个参数表示一共生成的元素个数。若生成一系列等差的浮点数，则用``linespace``更好些。

In [13]:
np.linspace(0, 2, 9 ) # 生成从 0 到 2 之间共 9 个数

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Python 的 list 类型可以与 Numpy 的数组类型 ndarray 互换，例如：

In [34]:
a = np.arange(10)
list(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 数组索引和切片

对于一维数组，numpy 的索引切片类似 Python list 类型的索引切片，例如：

In [23]:
a = np.arange(4, 10) # 生成一个从 4 到 9 之间的数组
a

array([4, 5, 6, 7, 8, 9])

In [22]:
a[2] # 数组 a 的第 3 个元素

6

In [19]:
a[2:4] # 数组 a 的第 3 与第 4 个元素

array([6, 7])

In [24]:
a[-1] # 数组 a 的最后一个元素

9

In [25]:
a[:: -1] # 数组 a 倒序

array([9, 8, 7, 6, 5, 4])

对于多维数组，Numpy 数组的索引和切片在**一个中括号**里面用逗号分隔不同维度，例如：

In [29]:
b = np.arange(12).reshape(3,4) # 创建一个 3 行 4 列的二维数组
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
b[1, 2] # 二维数组第 2 行第 3 列中的元素

6

In [31]:
b[1:3, 2] # 二维数组第 3 列中， 第 2 行到第 3 行的元素

array([ 6, 10])

In [32]:
b[2, :] # 第 3 行的全部元素

array([ 8,  9, 10, 11])

In [33]:
list(b)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

## 数组拼接

Numpy 中拼接两个数组用``append``函数。

In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
b = np.arange(3)
b

array([0, 1, 2])

In [38]:
np.append(a, b)

array([0, 1, 2, 3, 4, 0, 1, 2])

多个数组拼接，可以用``concatenate``。

In [39]:
c = np.arange(4)
c

array([0, 1, 2, 3])

In [40]:
np.concatenate((a, b, c)) # 注意里面还有一对小括号

array([0, 1, 2, 3, 4, 0, 1, 2, 0, 1, 2, 3])

## 数组运算

Numpy 可以对数组进行多种代数运算，例如：

In [43]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [42]:
b = np.arange(3, 7)
b

array([3, 4, 5, 6])

In [44]:
a - b # 两数组相减

array([-3, -3, -3, -3])

In [45]:
a + b # 两数组相加

array([3, 5, 7, 9])

In [46]:
a * 2 # 数组每个元素乘以一个数值

array([0, 2, 4, 6])

In [47]:
a ** 2 # 数组每个元素都平方

array([0, 1, 4, 9])

In [48]:
a > 2 # 数组每个元素与一个数值比较大小

array([False, False, False,  True])

In [49]:
c = np.array([[4.0, 5.0], [6.0, 7.0]])
c

array([[4., 5.],
       [6., 7.]])

In [50]:
c.transpose() # c 的转置矩阵

array([[4., 6.],
       [5., 7.]])

In [51]:
np.linalg.inv(c) # c 的逆矩阵

array([[-3.5,  2.5],
       [ 3. , -2. ]])

In [52]:
np.linalg.eig(c) # c 的特征值与特征向量

(array([-0.17890835, 11.17890835]),
 array([[-0.76729658, -0.57152478],
        [ 0.64129241, -0.82058481]]))

In [54]:
d = np.array([[1.0, 2.0], [3.0, 4.0]])
d

array([[1., 2.],
       [3., 4.]])

In [56]:
np.dot(c, d) # 矩阵 c 和 d 的乘积

array([[19., 28.],
       [27., 40.]])

In [57]:
np.multiply(c, d) # 矩阵 c 和 d 对应元素相乘

array([[ 4., 10.],
       [18., 28.]])

另外，Numpy 还有专门的二维数组的类型 Matrix，可以更方便地进行一些矩阵运算，感兴趣的读者可以参见官网。