# Numpy 简介
<hr>

Numpy (Numerical Python) 是 Python 语言一个重要的扩展库，支持大量的数组与矩阵运算，此外也提供大量的数学函数库，用于模仿数学软件 MatLab 的功能。Numpy 通常与其他库 SciPy（Scientific Python）和 Matplotlib（绘图库）一起使用。

Numpy 的主要特点是：

- 一个强大的 N 维数组对象 ndarray

- 矩阵运算、傅里叶变换、生成随机数功能等

使用 numpy 需要首先导入 numpy 包：

In [1]:
import numpy as np

## 创建数组
<hr>

用 Numpy 创建数组有多种方法。首先，Numpy 中的``array``函数可以直接将 Python 的 list 类型转化为 Numpy 的数组类型 ndarray。例如，一个一维数组：

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

一个二维数组：

In [3]:
b = [[1, 2], [3, 4]]
a = np.array(b)
a

array([[1, 2],
       [3, 4]])

注意，``array``函数中的小括号中要包括一个用中括号括起来的 list，不能直接写成 np.array(1, 2, 3, 4)。

Numpy 中的``zeros``函数可以创建元素值全为 0 的矩阵，``ones``函数可以创建元素值全为 1 的矩阵，而``empty``函数可以创建一个元素值任意的一个空矩阵。例如：

In [4]:
np.zeros((3, 4)) # 3 行 4 列的零矩阵

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3, 4)) # 3 行 4 列的一矩阵

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.empty((2, 3)) # 2 行 3 列的空矩阵

array([[0., 0., 0.],
       [0., 0., 0.]])

Numpy 中的``arange``函数可以生成一个等差数列的数组，例如：

In [7]:
np.arange(10) # 生成一个从 0 到 9 之间的数组，默认步长为 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5, 10) # 生成一个从 5 到 9 之间的数组，默认步长为 1

array([5, 6, 7, 8, 9])

In [9]:
np.arange(5, 10, 2) # 生成一个从 5 到 9 之间的数组，且步长为 2

array([5, 7, 9])

另外一个类似的函数为``linespace``，不同的地方在于：``arange``函数中第三个参数表示等差数组的步长，而``linespace``函数第三个参数表示一共生成的元素个数。若生成一系列等差的浮点数，则用``linespace``更好些。

In [10]:
np.linspace(0, 2, 9 ) # 生成从 0 到 2 之间共 9 个数

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Python 的 list 类型可以与 Numpy 的数组类型 ndarray 互换，例如：

In [11]:
a = np.arange(10)
list(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 库中常见的数组创建函数如下表所示：

|函数|描述|
|:--:|:--:|
|np.arrange(x, y, i)|创建一个由 x 到 y，以 i 为步长的数组|
|np.linspace(x, y, n)|创建一个由 x 到 y，等分为 n 个元素的数组|
|np.ones((m,n))|创建一个 m 行 n 列全是 1 的数组|
|np.empty((m,n))|创建一个 m 行 n 列全是 0 的数组|

numpy 创建的数组类型为 ndarray类型，它的常用属性如下表所示：

|函数|描述|
|:--:|:--:|
|ndarray.ndim|数组的行数|
|ndarray.shape|数组在每个维度上大小的整数元组|
|ndarray.size|数组中元素的个数|
|ndarray.dtype|数组中元素的数据类型|

In [12]:
a = np.ones((2,3))
a.ndim

2

In [13]:
a.shape

(2, 3)

In [14]:
a.size

6

In [15]:
a.dtype

dtype('float64')

## 数组索引和切片
<hr>

对于一维数组，numpy 的索引切片类似 Python list 类型的索引切片，例如：

In [16]:
a = np.arange(4, 10) # 生成一个从 4 到 9 之间的数组
a

array([4, 5, 6, 7, 8, 9])

In [17]:
a[2] # 数组 a 的第 3 个元素

6

In [18]:
a[2:4] # 数组 a 的第 3 与第 4 个元素

array([6, 7])

In [19]:
a[-1] # 数组 a 的最后一个元素

9

In [20]:
a[:: -1] # 数组 a 倒序

array([9, 8, 7, 6, 5, 4])

对于多维数组，Numpy 数组的索引和切片在**一个中括号**里面用逗号分隔不同维度，例如：

In [21]:
b = np.arange(12).reshape(3,4) # 创建一个 3 行 4 列的二维数组，reshape函数不改变数值，将原数组重组为一个指定行数列数的数组
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b[1, 2] # 二维数组第 2 行第 3 列中的元素

6

In [23]:
b[1:3, 2] # 二维数组第 3 列中， 第 2 行到第 3 行的元素

array([ 6, 10])

In [24]:
b[2, :] # 第 3 行的全部元素

array([ 8,  9, 10, 11])

In [25]:
list(b)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

## 数组拼接
<hr>

Numpy 中拼接两个数组用``append``函数。

In [26]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
b = np.arange(3)
b

array([0, 1, 2])

In [28]:
np.append(a, b)

array([0, 1, 2, 3, 4, 0, 1, 2])

多个数组拼接，可以用``concatenate``。

In [29]:
c = np.arange(4)
c

array([0, 1, 2, 3])

In [30]:
np.concatenate((a, b, c)) # 注意里面还有一对小括号

array([0, 1, 2, 3, 4, 0, 1, 2, 0, 1, 2, 3])

## 数组运算
<hr>

Numpy 可以对数组进行多种代数运算，例如：

In [31]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [32]:
b = np.arange(3, 7)
b

array([3, 4, 5, 6])

In [33]:
a - b # 两数组相减

array([-3, -3, -3, -3])

In [34]:
a + b # 两数组相加

array([3, 5, 7, 9])

In [35]:
a * 2 # 数组每个元素乘以一个数值

array([0, 2, 4, 6])

In [36]:
a ** 2 # 数组每个元素都平方

array([0, 1, 4, 9])

In [37]:
a > 2 # 数组每个元素与一个数值比较大小

array([False, False, False,  True])

In [38]:
c = np.array([[4.0, 5.0], [6.0, 7.0]])
c

array([[4., 5.],
       [6., 7.]])

In [39]:
c.transpose() # c 的转置矩阵

array([[4., 6.],
       [5., 7.]])

In [40]:
np.linalg.inv(c) # c 的逆矩阵

array([[-3.5,  2.5],
       [ 3. , -2. ]])

In [41]:
eigenvalues, eigenvectors = np.linalg.eig(c) # c 的特征值与特征向量
print('eigenvalues are ', eigenvalues)
print('eigenvectors are', eigenvectors)

eigenvalues are  [-0.17890835 11.17890835]
eigenvectors are [[-0.76729658 -0.57152478]
 [ 0.64129241 -0.82058481]]


In [42]:
d = np.array([[1.0, 2.0], [3.0, 4.0]])
d

array([[1., 2.],
       [3., 4.]])

In [43]:
np.dot(c, d) # 矩阵 c 和 d 的乘积

array([[19., 28.],
       [27., 40.]])

In [44]:
np.multiply(c, d) # 矩阵 c 和 d 对应元素相乘

array([[ 4., 10.],
       [18., 28.]])

numpy 库还有一些其他常用的函数，如下表所示：

|函数|描述|
|:--:|:--:|
|np.abs(x)|计算每个元素的绝对值|
|np.sqrt(x)|计算每个元素的平方根|
|np.squre(x)|计算每个元素的平方|
|np.sign(x)|计算每个元素的正负号|
|np.ceil(x)|计算每个元素向上取整的数值|
|np.floor(x)|计算每个元素向下取整的数值|
|np.exp(x)|计算每个元素的指数值|
|np.log(x),np.log10(x),np.log2(x)|计算每个元素的自然对数值，基于10、2的对数值|

另外，Numpy 还有专门的二维数组的类型 Matrix，可以更方便地进行一些矩阵运算，感兴趣的读者可以参见官网。

## 生成随机数
<hr>

numpy 包的`random`方法基本支持所有分布，并且能够一次生成多行多列的随机数, 例如：

In [45]:
import numpy as np

np.random.uniform(1, 10, [2,2]) # 生成 [1, 10] 内的均匀分布随机数， 2 行 2 列

array([[4.93275383, 3.51478805],
       [6.91968133, 8.75478504]])

In [46]:
np.random.uniform(1, 10, 5) # 生成 5 个 [1, 10] 内的均匀分布随机数

array([4.35431437, 6.72196329, 1.52868038, 4.5615047 , 4.96642431])

In [47]:
np.random.randint(1, 10, [2,2]) # 生成 [1, 10] 内的随机整数， 2 行 2 列

array([[7, 2],
       [3, 4]])

In [48]:
np.random.normal(5, 1, [2,2]) # 生成一个正态分布的随机数，均值为 5， 标准差为 1， 2 行 2 列

array([[4.65317243, 5.31332217],
       [5.17795779, 4.45061493]])

In [49]:
np.random.poisson(5, [2,2]) # 生成一个泊松分布的随机数，均值为 5， 2 行 2 列

array([[4, 1],
       [3, 6]])

numpy 还可以通过`random.seed()`参数设定随机数生成器的种子，同样的种子生成的随机数应该是相同的。

In [50]:
np.random.seed(500)
np.random.normal(5, 1, 6) # 生成 6 个正态分布的随机数，均值为 5， 标准差为 1

array([4.62263642, 5.16675892, 5.68280238, 6.92137877, 4.8029632 ,
       4.24012124])

另外 numpy 还可以通过`RandomState()`来定义一个随机数生成器对象，小括号里面的参数为随机数种子，然后用这个对象调用具体的各个随机分布生成器函数。例如：

In [51]:
rvs = np.random.RandomState(500)
rvs.normal(5, 1, 6) # 生成 6 个正态分布的随机数，均值为 5， 标准差为 1

array([4.62263642, 5.16675892, 5.68280238, 6.92137877, 4.8029632 ,
       4.24012124])

<script src="https://giscus.app/client.js"
        data-repo="robinchen121/book-Python-Data-Science"
        data-repo-id="R_kgDOKFdyOw"
        data-category="Announcements"
        data-category-id="DIC_kwDOKFdyO84CgWHi"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>

<!-- Toogle google translation -->
<div id="google_translate_element"></div>

<script type="text/javascript">
      function googleTranslateElementInit() {
        new google.translate.TranslateElement({ pageLanguage: 'zh-CN',
                  includedLanguages: 'en,zh-CN,zh-TW,ja,ko,de,ru,fr,es,it,pt,hi,ar,fa',
layout: google.translate.TranslateElement.InlineLayout.SIMPLE }, 'google_translate_element');
      }
</script>
<script type="text/javascript"
      src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
></script>
<br>