# Introduction to deep learning and Pytorch*
<hr>

Deep learning refers to the use of multi-layered neural networks, a field significantly advanced by Geoffrey Hinton, who was awarded the Nobel Prize in Physics in 2024 for his foundational contributions.

![Hinton](./pics/hinton.jpg)

Deep learning is widely applied in both research and everyday life, including computer vision (CV), such as facial recognition and autonomous driving; natural language processing (NLP), such as machine translation and chatbots; time series forecasting, such as demand forecasting and financial risk prediction; speech recognition, such as digital assistant Siri; Bioinformatics, such as gene and protein expression, etc.  

```{mermaid}
flowchart TD
    A(Deep Learning) --> B("Computer Vision (CV)")
    A --> C("Natrual Language Processing (NLP)")
    A --> D(Time Series Forecasting)
    A --> E(Speech Recognition)
    A --> F(Bioinfomatics)
    A --> G(...)

```

Pytorch is an open-sourced deep learning libarary originally developed by Meta. It provides a high level API that helps building deep learing algorithms and architectures easily.
- Think of its high-level API as a set of "ready-to-use building blocks" —— it hides the messy details so you can focus on easily designing and assembling powerful AI models.

Other major deep learning libraries include:

- TensorFlow (Google’s industry-standard for large-scale production).
- JAX (Google's high-performance framework designed for cutting-edge numerical computing)
- MXNet (Amazon).
- ...

## Tensor
<hr>

In deep learning, tensors are the fundamental building blocks of data. As multidimensional arrays of numbers, they generalize scalars, vectors, and matrices. 

- 0D Tensor: a scalar (a single number, like 5).

- 1D Tensor: a vector (a list of numbers, like [1, 2, 3]).

- 2D Tensor: a matrix (a table of numbers with rows and columns).

- 3D+ Tensors: data with more dimensions (like a color image with Height, Width, and Color Channels).

While similar to NumPy arrays, tensors are specifically designed to support automatic differentiation and GPU acceleration.

- Automatic differentiation works like a smart calculator that remembers every math step performed during a computation. As tensors go through operations such as addition or multiplication, PyTorch keeps track of how each result was produced. Later, when training a neural network, PyTorch goes backward through these recorded steps to figure out how much each tensor contributed to the final result. These contributions, called gradients, are automatically calculated and stored in the tensor’s `.grad` field, so the model knows how to adjust its parameters to improve performance.

- Deep learning involves millions of small mathematical operations, such as multiplying numbers together. Without a GPU (Graphics Processing Unit), the CPU (Central Processing Unit) must handle these computations alone. Although modern CPUs are fast, processing millions of operations still takes considerable time. GPUs are specifically designed to perform many of these small computations simultaneously. As a result, a task that might take a CPU an hour could be completed by a GPU in just a few seconds.

### Creation
<hr>

The following functions are used to initialize tensors from scratch or existing data.

- `torch.tensor()`: creates a tensor from data (like a list, tuple or NumPy array).

In [1]:
import torch

data = [[1, 2, 3], [4.2, 5 ,6]]

torch_data1 = torch.tensor(data) # from a list
print(torch_data1)
print(torch_data1.dtype) # get the data type of a tensor

tensor([[1.0000, 2.0000, 3.0000],
        [4.2000, 5.0000, 6.0000]])
torch.float32


In [2]:
import numpy as np

np_data = np.ones((2, 3))
torch_data2 = torch.tensor(np_data)
print(torch_data2)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


- Create with random or sequence values by `torch.zeros()`, `torch.ones()`, `torch.randn()`, `torch.arange()` or `torch.linspace()`.

In [3]:
shape = (3, 2)
torch.zeros(shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
torch.ones((1,3))

tensor([[1., 1., 1.]])

In [5]:
torch.randn((2,1)) # returns a tensor filled with random numbers from a normal distribution (mean 0, variance 1)

tensor([[0.0239],
        [0.4904]])

In [6]:
torch.arange(2, 20, 2) # torch.arange(start, end(exclusive), step) returns a 1D tensor with a range of values

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
torch.linspace(2, 20, 3) # torch.linspace() torch.linspace(start, end(inclusive), steps) returns a 1D tensor of steps equally spaced points between start and end

tensor([ 2., 11., 20.])

```{note}
When converting a NumPy array to a PyTorch Tensor, PyTorch inherits NumPy’s default floating-point precision *float64*. However, it is better to use the data type *float32* in deep learning for faster computation. 
```

- Use the `Tensor.float()` method to cast a tensor to the float32 data type for later training.

In [8]:
x = torch.arange(10)
print(x.dtype)
y = x.float()
print(y.dtype)

torch.int64
torch.float32


### Shape manipulation
<hr>

PyTorch has many shape manipulation functions because deep learning models frequently require tensors to be reshaped, transposed, or expanded between layers with different input requirements.

- View the shape of a tensor: `Tensor.shape`, `Tensor.ndim`.

In [9]:
x = torch.ones((3,4)) 
x.shape # another function .size() return same result as .shape

torch.Size([3, 4])

In [10]:
x.ndim # get the dimension of a tensor

2

. Change the shape of a tensor: `torch.squeeze()`, `torch.unsqueeze()`, `torch.flatten()`.

`torch.squeeze()` is to squeeze a tensor by removing the dimensions of size 1. Its syntex is:

<table>   
    <tr style="border-top:solid; border-bottom:solid">
        <th colspan=2 style="text-align:center">
            torch.squeeze(input, dim=None)
        </th>
    </tr>
    <tr>
        <td style="text-align:left">input</td>
        <td style="text-align:left">The input tensor.</td>
    </tr>
    <tr style="border-bottom:solid">
        <td style="text-align:left">dim</td>
        <td style="text-align:left">Given dimensions to squeeze.</td>
    </tr>
</table>

In [11]:
x = torch.ones((2, 1, 3, 1, 4))
x.shape

torch.Size([2, 1, 3, 1, 4])

In [12]:
y = torch.squeeze(x) # remove all the dimensions of size 1
y.shape

torch.Size([2, 3, 4])

In [13]:
y = torch.squeeze(x, 0)
y.shape # the shape does not change as the 0 dimension is not size 1

torch.Size([2, 1, 3, 1, 4])

In [14]:
y = torch.squeeze(x, dim=(1, 2)) # squeeze the size 1 dimension among the given dimensions
y.shape

torch.Size([2, 3, 1, 4])

- `torch.unsqueeze()` is used to add a new dimension of size 1 at the specified position to a tensor.

<table>   
    <tr style="border-top:solid; border-bottom:solid">
        <th colspan=2 style="text-align:center">
            torch.unsqueeze(input, dim)
        </th>
    </tr>
    <tr>
        <td style="text-align:left">input</td>
        <td style="text-align:left">The input tensor.</td>
    </tr>
    <tr style="border-bottom:solid">
        <td style="text-align:left">dim</td>
        <td style="text-align:left">Given dimension (should be lower equal then the number of dimensions of the tensor) to unsqueeze.</td>
    </tr>
</table>

````{tip}
`torch.unsqueeze()` for dim=d virtually wraps an extra pair of square brackets `[]` around the elements at the $d$-th nesting level of the tensor.
````

In [15]:
x = torch.tensor([1, 2, 3])
print(x)
x.shape

tensor([1, 2, 3])


torch.Size([3])

In [16]:
y = torch.unsqueeze(x, 0)
print(y)
y.shape

tensor([[1, 2, 3]])


torch.Size([1, 3])

In [17]:
y = torch.unsqueeze(x, 1)
print(y)
y.shape

tensor([[1],
        [2],
        [3]])


torch.Size([3, 1])

In [18]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)
y = torch.unsqueeze(x, 0)
print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]]])
torch.Size([1, 2, 3])


In [19]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)
y = torch.unsqueeze(x, 1)
print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
torch.Size([2, 1, 3])


In [20]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)
y = torch.unsqueeze(x, 2)
print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])
torch.Size([2, 3, 1])


- `torch.flattern()` is to reshape a tensor to be one-dimensional.

In [21]:
x = torch.tensor([[1, 2, 3], [5, 6, 7]])
print(x)
print(x.shape)
y = torch.flatten(x)
print(y.shape)
print(y)

tensor([[1, 2, 3],
        [5, 6, 7]])
torch.Size([2, 3])
torch.Size([6])
tensor([1, 2, 3, 5, 6, 7])


- change the shape of a tensor: `Tensor.view()`, `torch.reshape()`.

`Tensor.view(*shape)` return a new tensor with the same data as original but with a different shape. The returned tensor shares the same underlying memory with the original one, meaning changes to either tensor will be reflected in the other.

In [22]:
import torch
a = torch.randn(3, 4)
a

tensor([[ 0.7352,  0.6085, -0.1846,  0.0703],
        [ 1.2812, -1.1505,  0.7524, -0.8458],
        [-0.1252,  0.3921, -0.8374, -1.2715]])

In [23]:
b = a.view(4,3)
print(b)
b[0][0] = 1.5
print(a)

tensor([[ 0.7352,  0.6085, -0.1846],
        [ 0.0703,  1.2812, -1.1505],
        [ 0.7524, -0.8458, -0.1252],
        [ 0.3921, -0.8374, -1.2715]])
tensor([[ 1.5000,  0.6085, -0.1846,  0.0703],
        [ 1.2812, -1.1505,  0.7524, -0.8458],
        [-0.1252,  0.3921, -0.8374, -1.2715]])


In [24]:
a.view(12)

tensor([ 1.5000,  0.6085, -0.1846,  0.0703,  1.2812, -1.1505,  0.7524, -0.8458,
        -0.1252,  0.3921, -0.8374, -1.2715])

In [25]:
a.view(-1, 2)

tensor([[ 1.5000,  0.6085],
        [-0.1846,  0.0703],
        [ 1.2812, -1.1505],
        [ 0.7524, -0.8458],
        [-0.1252,  0.3921],
        [-0.8374, -1.2715]])

`torch.reshape(input, shape)` returns the same data as `input` with specified `shape`.

In [26]:
import torch
a = torch.randn(3, 4)
print(a)
torch.reshape(a, (2, 6))

tensor([[ 0.7997, -1.2565,  0.6466,  1.3083],
        [ 0.1427, -1.4108,  1.1638,  0.8129],
        [-0.8660,  0.0298,  0.1278, -0.0916]])


tensor([[ 0.7997, -1.2565,  0.6466,  1.3083,  0.1427, -1.4108],
        [ 1.1638,  0.8129, -0.8660,  0.0298,  0.1278, -0.0916]])

In [27]:
torch.reshape(a, (-1, 4))

tensor([[ 0.7997, -1.2565,  0.6466,  1.3083],
        [ 0.1427, -1.4108,  1.1638,  0.8129],
        [-0.8660,  0.0298,  0.1278, -0.0916]])

````{note}
When using `view()` or `reshape()`, `-1` acts as a placeholder, telling the system to automatically infer the size of that specific dimension.
````

### Concanetation
<hr>

- `torch.cat()` is to concanetate tensors at a given dimension.

<table>   
    <tr style="border-top:solid; border-bottom:solid">
        <th colspan=2 style="text-align:center">
            torch.cat(tensors, dim=0)
        </th>
    </tr>
    <tr>
        <td style="text-align:left">tesors</td>
        <td style="text-align:left">A sequence of tensors, which must have the same shape, except in the cat dimension.</td>
    </tr>
    <tr style="border-bottom:solid">
        <td style="text-align:left">dim</td>
        <td style="text-align:left">The given dimension (should be lower equal then the number of dimensions of the tensor) to concanetate.</td>
    </tr>
</table>

````{tip}
`torch.cat()` for dim=d virtually merges tensors by dissolving the adjacent boudaries of the $d$-th nesting level and blending their contents.
````

In [28]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
print(a)
print(b)
c = torch.cat((a, b), dim=0)
print(c)
print(c.shape)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])


In [29]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
print(a)
print(b)
c = torch.cat([a, b], dim=1)
print(c)
print(c.shape)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
torch.Size([2, 4])


In [30]:
a = torch.tensor([[1], [2]])
print(a.shape)
b = torch.tensor([[3], [4]])
torch.cat([a,b])

torch.Size([2, 1])


tensor([[1],
        [2],
        [3],
        [4]])

In [31]:
torch.cat([a, b], dim=1)

tensor([[1, 3],
        [2, 4]])

- `torch.stack()` is to concanetate tensors along with a **new** dimension.

<table>   
    <tr style="border-top:solid; border-bottom:solid">
        <th colspan=2 style="text-align:center">
            torch.stack(tensors, dim=0)
        </th>
    </tr>
    <tr>
        <td style="text-align:left">tesors</td>
        <td style="text-align:left">A sequence of tensors to concanetate and the tensors need to be of the same size.</td>
    </tr>
    <tr style="border-bottom:solid">
        <td style="text-align:left">dim</td>
        <td style="text-align:left">The given dimension to concanetate and shoule be between 0 and the number of dimensions of concatenated tensors (inclusive).</td>
    </tr>
</table>

````{note}
If each tensor has shape (m, n) and there are k tensors to stack, the resulting shape is (k, m, n) for `dim=0`, (m, k, n) for `dim=1`, and (m, n, k) for `dim=2`. More generally, `dim=d` inserts a new dimension at position d, whose size is k.
````

In [32]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(a.shape)
c = torch.stack([a, b], dim=0) # stack a, b along dimension 0 to [a, b]
print(c)
print(c.shape)
print(c[0])

torch.Size([2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


````{tip}
`torch.stack()` for dim=d virtually stacks tensors by blending the contents of the $d$-th nested level and wraps an extra pair of square brackets around them.
````

In [33]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])

c = torch.stack([a, b], dim=1) # stack a, b along dimension 1
print(c)
print(c.shape)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
torch.Size([2, 2, 3])


In [34]:
c = torch.stack([a, b], dim=2) # stack a, b along dimension 2
print(c)
print(c.shape)
print(c[0])

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])
torch.Size([2, 3, 2])
tensor([[1, 7],
        [2, 8],
        [3, 9]])


````{note}
Literally, `torch.stack(tensors, dim=d)` first unsqueeze each tensor along the given dimension d and then concanetate them at the given dimension d.
````

In [35]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
x = torch.unsqueeze(a, 1)
print(x)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])


In [36]:
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
y = torch.unsqueeze(b, 1)
print(y)

tensor([[[ 7,  8,  9]],

        [[10, 11, 12]]])


In [37]:
torch.cat([x, y], dim=1)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])

In [38]:
torch.cat([x, y], dim=1)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])

In [39]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
x = torch.unsqueeze(a, 0)
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6]]])


In [40]:
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
y = torch.unsqueeze(b, 0)
print(y)

tensor([[[ 7,  8,  9],
         [10, 11, 12]]])


In [41]:
torch.cat([x, y], dim=0)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

### Expansion
<hr>

- `.repeat()` is to repeat a tensor along the specified dimensions.

In [42]:
x = torch.tensor([1, 2, 3])
x.repeat((2, 3))

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]])

- `torch.full()` is to creat a tensor of specified size with **one given value**.

<table>   
    <tr style="border-top:solid; border-bottom:solid">
        <th colspan=2 style="text-align:center">
            torch.full(size, fill_value)
        </th>
    </tr>
    <tr>
        <td style="text-align:left">size</td>
        <td style="text-align:left">A list, tuple, or torch.Size. The specified size of the output tensor.</td>
    </tr>
    <tr style="border-bottom:solid">
        <td style="text-align:left">fill_value</td>
        <td style="text-align:left">A scalar. The given value to fill the tensor with.</td>
    </tr>
</table>

In [43]:
a = 2.3
torch.full((3,4), a)

tensor([[2.3000, 2.3000, 2.3000, 2.3000],
        [2.3000, 2.3000, 2.3000, 2.3000],
        [2.3000, 2.3000, 2.3000, 2.3000]])